CREATE TABLE couples
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    first_user_id  BIGINT                                  NOT NULL,
    second_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_couples PRIMARY KEY (id)
);

ALTER TABLE users
    ADD active_couple_id BIGINT;

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX couple_search_index ON couples (first_user_id, second_user_id, status);

ALTER TABLE couples
    ADD CONSTRAINT FK_COUPLES_ON_FIRST_USER FOREIGN KEY (first_user_id) REFERENCES users (id);

ALTER TABLE couples
    ADD CONSTRAINT FK_COUPLES_ON_SECOND_USER FOREIGN KEY (second_user_id) REFERENCES users (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ACTIVE_COUPLE FOREIGN KEY (active_couple_id) REFERENCES couples (id);

ALTER TABLE users
DROP
COLUMN friend_code;

ALTER TABLE users
    ADD friend_code VARCHAR(255) NOT NULL;