CREATE TABLE days
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    couple_id   BIGINT                                  NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    cover_photo VARCHAR(255),
    date        date                                    NOT NULL,
    CONSTRAINT pk_days PRIMARY KEY (id)
);

ALTER TABLE couples
    ADD anniversary_date date;

ALTER TABLE days
    ADD CONSTRAINT FK_DAYS_ON_COUPLE FOREIGN KEY (couple_id) REFERENCES couples (id);

ALTER TABLE users
DROP
COLUMN friend_code;

ALTER TABLE users ADD friend_code VARCHAR(255);
UPDATE users SET friend_code = 'USER_' || id WHERE friend_code IS NULL;
ALTER TABLE users ALTER COLUMN friend_code SET NOT NULL;