CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    aggregate_type VARCHAR(255),
    aggregate_id   BIGINT,
    event_type     VARCHAR(255),
    status         VARCHAR(255),
    exchange_name  VARCHAR(255)                            NOT NULL,
    routing_key    VARCHAR(255)                            NOT NULL,
    payload        JSONB                                   NOT NULL,
    retry_count    INTEGER                                 NOT NULL,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id)
);