CREATE TABLE couple_invite
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    sender_user_id   BIGINT                                  NOT NULL,
    receiver_user_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_coupleinvite PRIMARY KEY (id)
);

ALTER TABLE couple_invite
    ADD CONSTRAINT FK_COUPLEINVITE_ON_RECEIVER_USER FOREIGN KEY (receiver_user_id) REFERENCES users (id);

ALTER TABLE couple_invite
    ADD CONSTRAINT FK_COUPLEINVITE_ON_SENDER_USER FOREIGN KEY (sender_user_id) REFERENCES users (id);