CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    modified_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    hash_token  VARCHAR(512)                            NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    expires_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_hashtoken UNIQUE (hash_token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT FK_REFRESH_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);